### ISSUE TITLE
BBQ in HTA, IE6/7 - hidden iframe cannot load .hta file

### ISSUE THREAD

**Issue by zspitz** [cowboy/jquery-bbq#12]
The IE6/7 hashchange fix breaks down in an HTA (HTML Application), as the source of the hidden iframe is set to the hta url. But IE doesn't treat an .hta as a regular HTML file, but rather as a file to be downloaded. Under default settings, IE prompts the user to download the .hta file; and also raises an error, as the iframe.document is null.
On the other hand, an hta has no history, back, or forward, either - attempting to change the window.location.href to another file results in that other file being opened in IE - so the 'back button' of BBQ is rather useless.
Nevertheless, BBQ is still very useful for passing state to another instance of an HTA via the command line, and for maintaining state history within the current instance - the hash alone can be changed without difficulty.

I can suggest a possible fix - allow disabling the IE6/7 fix, even under the appropriate IE version; and the internal get_history/set_history should act on an internal array of changed hashes.

**Comment by cowboy** [comment]
If the internal Iframe is removed in IE6/7, the browser's back button will navigate to the previous non-hashchanged page (skipping all hash changes), so that's not a realistic option.

In the [jQuery hashchange plugin "domain" branch](http://github.com/cowboy/jquery-hashchange/tree/domain), I've added an additional option whereby you can manually specify the Iframe source by doing `$.hashchangeIframeSrc = 'path/to/file.html'`. Does that sound like it might help?

Feel free to replace the hashchange event embedded in the copy of BBQ you're using with this one if you'd like to try it out.

**Comment by cowboy** [comment]
Did you try this? I'd love some feedback, thanks.

**Comment by cowboy** [comment]
Closing this, as hashchange event 1.3 (that will be integrated as of BBQ 1.3) should address this issue.
