### ISSUE TITLE
jQuery.param.fragment strange behavior

### ISSUE THREAD

**Issue by vvo** [cowboy/jquery-bbq#3]
Hello (again), i think i'm very unlucky because there isn't a lot of issues for BBQ and it's my second one !

Also i dunno if it's really a bug or not so, a nice example page to show :

http://jsbin.com/exuvu/6#hello=yes

We have this behavior on our website, jQuery.param.fragment without parameters return window.location (from the doc but i think what you means is the current window.location.hash modified..) without the # in it.

But jQuery.param.fragment('', 'hello=yes') returns #hello=yes so we can't compare values without stripping the #.

Is this the desired behavior ?

**Comment by cowboy** [comment]
I'm not sure what you're asking. Just like `$.param.fragment( '/some/url.html', 'a=1' )` will try to merge fragment params "a=1" into url "/some/url.html" and return "/some/url.html#a=1", `$.param.fragment( '', 'a=1' )` will try to merge fragment params "a=1" into url "" and return "#a=1".

And you probably shouldn't compare BBQ "params" fragments as strings, because in different browsers (since objects' property order is unsorted and not guaranteed) there's the possibility that the individual params could be encoded in different orders.

**Comment by vvo** [comment]
What i'm trying to explain is that .fragment have different behavior when you call it with no params :

if your url is http://google.com/#q=yes

$.param.fragment() return "q=yes" without the #

while $.param.fragment('', 'q=yes') will return #q=yes so i was thinking that the behavior was different.

**Comment by cowboy** [comment]
That's the expected behavior, the documentation for [jQuery.param.fragment](http://benalman.com/code/projects/jquery-bbq/docs/files/jquery-ba-bbq-js.html#jQuery.param.fragment) states that the method returns:

> The parsed fragment (hash) string, with any leading “#” removed.

**Comment by cowboy** [comment]
I think I actually need to update the documentation for `jQuery.param.fragment (build url)` to indicate that it returns:

> A URL with a urlencoded fragment (hash) in the format ‘#a=b&c=d&e=f’.

**Comment by vvo** [comment]
Ok thank you for your anwsers, this is now closed
